@FamilyHubs.Mock_Hsda.Api_HostAddress = http://localhost:5156

GET {{FamilyHubs.Mock_Hsda.Api_HostAddress}}/
Accept: application/json

###

GET {{FamilyHubs.Mock_Hsda.Api_HostAddress}}/services/ac148810-d857-441c-9679-408f346de14b
Accept: application/json

###

GET {{FamilyHubs.Mock_Hsda.Api_HostAddress}}/services/nonexistant
Accept: application/json

###

GET {{FamilyHubs.Mock_Hsda.Api_HostAddress}}/services?page=4&per_page=10
Accept: application/json
X-Mock-Response-Id: Pagination

###

GET {{FamilyHubs.Mock_Hsda.Api_HostAddress}}/services?page=1&per_page=50
Accept: application/json
X-Mock-Response-Id: Empty

###

GET {{FamilyHubs.Mock_Hsda.Api_HostAddress}}/services
Accept: application/json
X-Mock-Response-Id: 500

###
