name: Set basic auth for web app
description: Configures basic auth for web app

inputs:

  source_path_and_name: 
    required: true
    description: Path and name of file to upload

  web_app_name:
    required: true
    description: Name of web app to upload to

  publish_profile:
    required: true
    description: Publish profile for web app

  target_path_and_name: 
    required: true
    description: Target path and name of file in the web app

  optional_web_app_restart:
    required: false
    description: Whether to restart the web app
    default: false

  web_app_resource_group:
    required: false
    description: Resource group for web app requiring restart

runs:
  using: composite
  steps:
      - name: Add Basic Auth Credentials To applicationHost.xdt (If Auth Required)
        id: optional_add_basic_auth
        if: ${{ vars.WEB_APPS_REQUIRE_BASIC_AUTH == 'true' }}
        shell: bash
        run: |
          if [[ -f "$APP_HOST_FILE" ]]; then
            cp "$APP_HOST_FILE" .
            BASIC_AUTH_BASE64_CREDS=$(echo -n "${{ secrets.WEB_APPS_BASIC_AUTH_USER }}:${{ secrets.WEB_APPS_BASIC_AUTH_PASSWORD }}" | base64)
            sed -i 's|${WEBSITE_BASIC_AUTH_BASE64_ENCODING}|'"$BASIC_AUTH_BASE64_CREDS|g" "./applicationHost.xdt"
            echo "app_host_file_exists=true" >> $GITHUB_OUTPUT
          else
            echo "applicationHost.xdt file not found (is optional)"
            echo "app_host_file_exists=false" >> $GITHUB_OUTPUT
          fi          
        env:
          APP_HOST_FILE: ./out/applicationHost.xdt

      - name: Upload applicationHost.xdt To Web App (If Auth Required)
        if: ${{ vars.WEB_APPS_REQUIRE_BASIC_AUTH == 'true' && steps.optional_add_basic_auth.outputs.app_host_file_exists == 'true' }}
        uses: ./.github/actions/upload-file-to-web-app
        with:
          source_path_and_name: ./applicationHost.xdt
          web_app_name: ${{ env.APP_NAME }}
          publish_profile: ${{ steps.fetch_profile.outputs.publish_profile }}
          target_path_and_name: /site/applicationHost.xdt
          optional_web_app_restart: true
          web_app_resource_group: ${{ env.RESOURCE_GROUP }}
