name: Azure IP Whitelist
description: Add or Remove an IP Address to the Azure SQL Whitelist

inputs:
  ip_address:
    required: true
    type: string
  action:
    required: true
    type: choice
    options:
      - "Add"
      - "Remove"
  az_resource_group:
    required: true
    type: string
  az_sql_server_name:
    required: true
    type: string
  az_firewall_rule_name:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Add to Whitelist
      if: ${{ inputs.action == 'Add' }}
      shell: bash
      run: |
        az sql server firewall-rule create --resource-group ${{ inputs.az_resource_group }} --server ${{ inputs.az_sql_server_name }} --name ${{ inputs.az_firewall_rule_name }} --start-ip-address ${{ inputs.ip_address }} --end-ip-address ${{ inputs.ip_address }} &> /dev/null

    - name: Remove from Whitelist
      if: ${{ inputs.action == 'Remove' }}
      shell: bash
      run: |
        az sql server firewall-rule delete --resource-group ${{ inputs.az_resource_group }} --server ${{ inputs.az_sql_server_name }} --name ${{ inputs.az_firewall_rule_name }} &> /dev/null