// <auto-generated />
using System;
using FamilyHubs.Notification.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyHubs.Notification.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230629121644_AddMultiEmailAndApiKeysSchema")]
    partial class AddMultiEmailAndApiKeysSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyHubs.Notification.Data.Entities.Notified", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SentNotificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SentNotificationId");

                    b.ToTable("Notified");
                });

            modelBuilder.Entity("FamilyHubs.Notification.Data.Entities.SentNotification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiKeyType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SentNotifications");
                });

            modelBuilder.Entity("FamilyHubs.Notification.Data.Entities.TokenValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NotificationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SentNotificationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SentNotificationId");

                    b.ToTable("TokenValues");
                });

            modelBuilder.Entity("FamilyHubs.Notification.Data.Entities.Notified", b =>
                {
                    b.HasOne("FamilyHubs.Notification.Data.Entities.SentNotification", null)
                        .WithMany("Notified")
                        .HasForeignKey("SentNotificationId");
                });

            modelBuilder.Entity("FamilyHubs.Notification.Data.Entities.TokenValue", b =>
                {
                    b.HasOne("FamilyHubs.Notification.Data.Entities.SentNotification", null)
                        .WithMany("TokenValues")
                        .HasForeignKey("SentNotificationId");
                });

            modelBuilder.Entity("FamilyHubs.Notification.Data.Entities.SentNotification", b =>
                {
                    b.Navigation("Notified");

                    b.Navigation("TokenValues");
                });
#pragma warning restore 612, 618
        }
    }
}
