name: Deploy Websites Only
run-name: Deploy websites only to ${{ github.event_name == 'push' && 'Development' || inputs.environment }}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.event_name == 'push' && 'Development' || inputs.environment }}"
  cancel-in-progress: true

on:
  push:
    branches:
      - feature/FHB-1295-claim-google-search-ownership
  workflow_dispatch:
    inputs:
      environment:
        description: The environment target for deployment
        default: 'Development'
        type: choice
        options:
          - 'Development'
          - 'Test'
          - 'Test2'
          - 'Pre-production'
          - 'Production'

permissions:
  id-token: write
  contents: read

jobs:
  build-projects-upload-artifacts:
    name: Build - ${{ matrix.job_name }}
    strategy:
      fail-fast: true
      matrix:
        project: [ src/ui/connect-ui/,
                   src/ui/find-ui/,
                   src/ui/idam-maintenance-ui/,
                   src/ui/manage-ui/
        ]
        include:
          - project: src/ui/connect-ui/
            publish_project: FamilyHubs.Referral.Web
            job_name: Connect UI
          - project: src/ui/find-ui/
            publish_project: FamilyHubs.ServiceDirectory.Web
            job_name: Find UI
          - project: src/ui/idam-maintenance-ui/
            publish_project: FamilyHubs.Idams.Maintenance.UI
            job_name: IDAM Maintenance UI
          - project: src/ui/manage-ui/
            publish_project: FamilyHubs.ServiceDirectory.Admin.Web
            job_name: Manage UI
    uses: ./.github/workflows/build-upload-artifact.yml
    with:
      project: ${{ matrix.project }}
      publish_project: ${{ matrix.publish_project }}
      dotnet_version: ${{ matrix.dotnet_version_override || vars.DOTNET_VERSION }}
      job_name: ${{ matrix.job_name }}
  
  deploy-ui-services:
    name: ${{ matrix.job_name }}
    needs: [ build-projects-upload-artifacts ]
    strategy:
      matrix:
        artifact_name: [ connect-ui,
                         find-ui,
                         idam-maintenance-ui,
                         manage-ui
        ]
        include:
          - artifact_name: connect-ui
            job_name: Deploy - Connect UI
            keyvault_app_prefix: CONNECT-UI
            project_name: FamilyHubs.Referral.Web
            azure_app_name: as-fh-referral-ui

          - artifact_name: find-ui
            job_name: Deploy - Find UI
            keyvault_app_prefix: FIND-UI
            project_name: FamilyHubs.ServiceDirectory.Web
            azure_app_name: as-fh-sd-ui

          - artifact_name: idam-maintenance-ui
            job_name: Deploy - IDAM Maintenance UI
            keyvault_app_prefix: IDAM-MAINTENANCE-UI
            project_name: FamilyHubs.Idams.Maintenance.UI
            azure_app_name: as-fh-idam-maintenance-ui

          - artifact_name: manage-ui
            job_name: Deploy - Manage UI
            keyvault_app_prefix: MANAGE-UI
            project_name: FamilyHubs.ServiceDirectory.Admin.Web
            azure_app_name: as-fh-sd-admin-ui
    uses: ./.github/workflows/deploy-service.yml
    with:
      environment: ${{ github.event_name == 'push' && 'Development' || inputs.environment }}
      artifact_name: ${{ matrix.artifact_name }}
      keyvault_app_prefix: ${{ matrix.keyvault_app_prefix }}
      project_name: ${{ matrix.project_name }}
      project_type: ui
      azure_app_name: ${{ matrix.azure_app_name }}
    secrets: inherit
